### ISSUE TITLE
/video/position is not applied

### ISSUE THREAD

**Issue by bensteUEM** [bitfocus/companion-module-songbeamer-osc#16]
Using
debug: Sent OSC to 192.168.0.28:10023 with /video/position and [{"type":"f","value":0.0003472222222222222}]
(0.5 Minutes)

(input value divided by 24 by 60 ... in order to match "full days" from endpoint description
does not have any effect on video playback

**Comment by bensteUEM** [comment]
Requesting Video position does send a reply but it is always the same value therefore likely wrong

Video 1
```
debug: Sent OSC to 192.168.0.28:10023 with /video/position and []
debug: Received OSC message from: {"address":"192.168.0.28","family":"IPv4","port":10023,"size":24}
debug: OSC Content is: {"address":"/video/position","args":[{"type":"f","value":0.00034722223062999547}]}
```

Video 2
```
debug: Sent OSC to 192.168.0.28:10023 with /video/position and []
debug: Received OSC message from: {"address":"192.168.0.28","family":"IPv4","port":10023,"size":24}
debug: OSC Content is: {"address":"/video/position","args":[{"type":"f","value":0.00034722223062999547}]}
```

**Comment by bensteUEM** [comment]
reported /video/position still seems to be wrong with Songbeamer 6.04a
```
system: ** Log cleared **
debug: Sent OSC to 192.168.0.28:10023 with /video/position and [{"type":"s","value":"text"}]
debug: Received OSC message from: {"address":"192.168.0.28","family":"IPv4","port":10023,"size":24}
debug: OSC Content is: {"address":"/video/position","args":[{"type":"f","value":0.0006944444612599909}]}
debug: /video/position 0.0006944444612599909
warn: There is a bug in Songbeamer 6.0.4a which always results in the same value #16
```

**Comment by bensteUEM** [comment]
@Lasibian if the function is not yet implemented i wouldn't it be easier to return nothing instead of returning some number?

**Comment by Lasibian** [comment]
It should report 0.0 until it is fully implemented. But if you send a position value, it will be remembered. I would have to remove the partial implementation to avoid returning a value.

**Comment by bensteUEM** [comment]
@Lasibian any updated on the OSC implementation?
Will this be part of a future songbeamer release?

**Comment by Lasibian** [comment]
I will add it in the next version. The data type will be changed to double. The node /video/length will also be changed to double.

Note: I don't have a reference implementation where I can test the new double type. So if there are any issues, let me know.

**Comment by bensteUEM** [comment]
- [ ] please reduce frequency of /video/position updates sent by songbeamer in order to improve system performance.

**Comment by bensteUEM** [comment]
All other items resolved - therefore code merged into dev ... However without improvement on Songbeamer side this will cause the system to "freeze" due to flooding of OSC messages when playing a video
