### ISSUE TITLE
/livevideo/state does not work

### ISSUE THREAD

**Issue by bensteUEM** [bitfocus/companion-module-songbeamer-osc#18]
On a single display configuration both play and stop do not have an effect on live video playback (using webcam)

debug: Sent OSC to 192.168.0.28:10023 with /livevideo/state and [{"type":"s","value":"play"}]
debug: Sent OSC to 192.168.0.28:10023 with /livevideo/state and [{"type":"s","value":"stop"}]

**Comment by Lasibian** [comment]
Yes, it's the same issue as #39.

**Comment by bensteUEM** [comment]
Following 6.04c documentation this start/stop should be available

**Comment by bensteUEM** [comment]
int response received with Songbeamer 6.04c update

```
system: ** Log cleared **
debug: Received OSC message from: {"address":"192.168.0.28","family":"IPv4","port":10023,"size":28}
debug: OSC Content is: {"address":"/livevideo/state","args":[{"type":"i","value":0}]}
warn: received a message with an unknown address - not implemented
debug: Received OSC message from: {"address":"192.168.0.28","family":"IPv4","port":10023,"size":28}
debug: OSC Content is: {"address":"/livevideo/state","args":[{"type":"i","value":1}]}
warn: received a message with an unknown address - not implemented
```

@Lasibian  - wrong response type?

**Comment by bensteUEM** [comment]
Trying to change it with OSC doesn't work either ...

**Comment by bensteUEM** [comment]
with 6.04c 
- [x] updates are send from songbeamer to OSC
- [ ] stop change is applied using OSC?
- [ ] start livevideo is applied?

**Comment by bensteUEM** [comment]
- [ ] Preset boolean only applied once changed in GUI once
- [ ] change logic of action to include "should excecute" like others
