### ISSUE TITLE
presentation state not applied with named params

### ISSUE THREAD

**Issue by bensteUEM** [bitfocus/companion-module-songbeamer-osc#39]
```
debug: Sent OSC to 192.168.0.28:10023 with /presentation/state and [{"type":"s","value":"logo"}]
debug: Received OSC message from: {"address":"192.168.0.28","family":"IPv4","port":10023,"size":28}
debug: OSC Content is: {"address":"/presentation/state","args":[{"type":"i","value":0}]}
debug: presentation/state 0
debug: Sent OSC to 192.168.0.28:10023 with /presentation/state and [{"type":"s","value":"background"}]
debug: Received OSC message from: {"address":"192.168.0.28","family":"IPv4","port":10023,"size":28}
debug: OSC Content is: {"address":"/presentation/state","args":[{"type":"i","value":0}]}
debug: presentation/state 0
```
@Lasibian  - did you change the required params for presentation states?
The code used to work before (but didn't send feedback) 
Previously it used to be text params now the response seem to be numbers?

Ever since the 6.04 release a number instead of a string state is returned and the text values are not applied.

**Comment by bensteUEM** [comment]
With 6.04c Update neither int nor string change presentation state.
Seems to be a regression bug with the API?
(even though a response with the correct "updated" state is received ...

**Comment by bensteUEM** [comment]
update did also break /video/state
neither string nor int value is accepted for changes

**Comment by Lasibian** [comment]
It works fine for me. Please try the demo application from https://download.songbeamer.de/SongBeamer-OSC.zip

**Comment by bensteUEM** [comment]
I've tried the Demo app you provided with the 6.04c release and even this one sends inconsistent data... (tested for presentation state)

black/background is sent as str e.g. "black" 
logo is sent as int - 3
page state is missing completly

**Comment by bensteUEM** [comment]
after restarting songbeamer both demo app and companion module work with presentation state again - looks like Songbeamer somehow ended up in an unstable state not accepting OSC anymore...

**Comment by bensteUEM** [comment]
/video/state also work!

**Comment by Lasibian** [comment]
There is indeed a bug that SongBeamer needs to be restarted after activating OSC.

The demo app is inconsistent when sending presentation start. This is intentional, so that both modes get tested.
