### ISSUE TITLE
/xinfo /info report wrong Songbeamer version

### ISSUE THREAD

**Issue by bensteUEM** [bitfocus/companion-module-songbeamer-osc#42]
Both functions report "6.04" instead of "6.04a" which is installed
```
system: ** Log cleared **
debug: Sent OSC to 192.168.0.28:10023 with /xinfo and []
debug: Received OSC message from: {"address":"192.168.0.28","family":"IPv4","port":10023,"size":64}
debug: OSC Content is: {"address":"/xinfo","args":[{"type":"s","value":"192.168.0.28"},{"type":"s","value":"osc-server"},{"type":"s","value":"SongBeamer"},{"type":"s","value":"6.04"}]}
warn: received a message with an unknown address - not implemented
debug: Sent OSC to 192.168.0.28:10023 with /info and []
debug: Received OSC message from: {"address":"192.168.0.28","family":"IPv4","port":10023,"size":56}
debug: OSC Content is: {"address":"/info","args":[{"type":"s","value":"V2.08"},{"type":"s","value":"osc-server"},{"type":"s","value":"SongBeamer"},{"type":"s","value":"6.04"}]}
```
Followup form #20 

- [x] Check that songbeamer sends correct version information

**Comment by bensteUEM** [comment]
- [ ] confirm that OSC Server version "v2.08" is set on purpose and is not a leftover from /Xair

**Comment by Lasibian** [comment]
v2.08 is indeed a leftover from X32. I'm not sure what do use here for SongBeamer.

I will add the version letter to the response.

**Comment by bensteUEM** [comment]
do we even need /xinfo ?

**Comment by Lasibian** [comment]
The letter will be reported in SongBeamer 6.04c.

v2.08 is still there, I'm not sure what to put there instead.

/xinfo and /info are in the "ancestor class" of the SongBeamer OSC class. I use them for my X32 app. So I prefer to leave them there. I'd recommend using /xinfo because that seems to be the newer command, and it doesn't have the v2.08 in the response.

**Comment by Lasibian** [comment]
I believe that v2.08 is the version of the osc server component. I'll leave it there as it is. The SongBeamer version is now correctly reported as the last value.

**Comment by bensteUEM** [comment]
was fixed in some release.
