### ISSUE TITLE
weird characters in SongBeamer_OSC.docx

### ISSUE THREAD

**Issue by nugatritter** [bitfocus/companion-module-songbeamer-osc#50]
In `documents/SongBeamer_OSC.docx` in columns `Action`, `Feedback` and `Status` are wired characters.
[SongBeamer_OSC.pdf](https://github.com/bitfocus/companion-module-songbeamer-osc/files/13411051/SongBeamer_OSC.pdf)

**Comment by bensteUEM** [comment]
@nugatritter thanks for reporting - for some reason WebDings font was selected. It wasn't installed on my system therefore didn't show as such :) I've pushed a new version using a default font which should be available for everyone.
